### ISSUE TITLE
cmsense for method=gformula

### ISSUE THREAD

**Issue by martin-urner** [BS1125/CMAverse#20]
Hi Linda,

The sensitivity analysis for the g-formula method produces an error message "object 'out.index' not found". I assume that the reason for this error message is in cmsens.R, line 158:  

if (model %in% c("rb", "wb", "msm", "g-formula", "ne")) out.index <- 1:6.

Should it be "gformula" instead of "g-formula"?

Thank you very much for this amazing R package!! Very best,

Martin

**Comment by BS1125** [comment]
Fixed in commit 60085fc
Thank you!
