### ISSUE TITLE
different adjustments

### ISSUE THREAD

**Issue by Guoguo-ux** [BS1125/CMAverse#24]
Are different adjustments allowed in this packages? For example, confounders C1 and C2 need to be controled in exposure-outcome model, but C1 and C3 need to be controled in exposure-mediator model. Can I use this package to perform this analysis?

**Comment by BS1125** [comment]
Hi, you can fit the regression models and specify them as yreg and mreg.

**Comment by seanharrigan** [comment]
Hello, 

I have also been wondering about this. Would you mind showing an example of how you would specify the models as the yreg and mreg inputs in the cmest function?

Using an example similar to the CMAverse vignette, let's say I am interested in adjusting for C1, C2, and C3 in the yreg, but only C1 and C2 in the mreg model. How would I define this in the cmest function below?

```
est <- cmest(data = data, model = "rb", outcome = "Y", exposure = "A",
             mediator = "M1", basec = c("C1", "C2", "C3"), EMint = FALSE,
             mreg = list("logistic"), yreg = "logistic",
             astar = 0, a = 1, mval = list(1),
             estimation = "paramfunc", inference = "delta", nboot = 20)

```
Thanks very much in avance!

**Comment by BS1125** [comment]
Hi, please try model like this and let me know if there is any error:
est <- cmest(data = data, model = "rb", outcome = "Y", exposure = "A",
             mediator = "M", basec = c("C1", "C2", "C3"), EMint = FALSE,
             mreg = list(lm(M~A+C1+C2, data = data)), yreg = lm(Y~A+M+C1+C2+C3, data = data),
             astar = 0, a = 1, mval = list(1),
             estimation = "imputation", inference = "bootstrap", nboot = 20)

**Comment by Guoguo-ux** [comment]
> Hi, please try model like this and let me know if there is any error: est <- cmest(data = data, model = "rb", outcome = "Y", exposure = "A", mediator = "M", basec = c("C1", "C2", "C3"), EMint = FALSE, mreg = list(lm(M ~ A+C1+C2, data = data)), yreg = lm(Y ~ A+M+C1+C2+C3, data = data), astar = 0, a = 1, mval = list(1), estimation = "imputation", inference = "bootstrap", nboot = 20)

Thanks for your help. This way is effective. Although there is no error, I found some warning:
Warning messages:
1: In yreg %in% c("coxph", "aft_exp", "aft_weibull") && !is.null(event) :
  'length(x) = 21 > 1' in coercion to 'logical(1)'
2: In cmest(data = chns_diabete_enviro5, model = "rb", outcome = "diabete_time",  :
  event is ignored when yreg is not character
3: In regrun() :
  When model is 'rb' or 'gformula', make sure there is no mediator-mediator interaction in yreg; ignore this warning if there isn't

1 and 3 appear regardless of the yreg (lm or coxph or other), but 2 appear when yreg is coxph. Are these warning messages improtant?

this is my code:
cmest(data = chns_diabete_enviro5, model = "rb", outcome = "diabete_time", 
              exposure = "greensmean5q", mediator = c( "no2mean5"), 
              basec = c("age_c", "gender", "bmi_c2", "edu_degree", "smoke_base", "drink_base", "index"), 
              EMint = T, event = c("diabete_status"), 
              mreg = list(lm(no2mean5 ~ greensmean5q+index, data = chns_diabete_enviro5)), 
              yreg = coxph(Surv(diabete_time, diabete_status) ~ greensmean5q*no2mean5 + age_c + gender + bmi_c2 + edu_degree + smoke_base +drink_base+index, data = chns_diabete_enviro5),
              astar = 0, a = 1, mval = list(1), multimp = F, yval = 0,
              estimation = "imputation", inference = "bootstrap", nboot = 10,
              boot.ci.type = "bca")

thanks again

**Comment by BS1125** [comment]
Hi, you can ignore the warnings. The second one just means the 'event' variable is specified in the 'yreg' argument rather than the 'event' argument.

**Comment by Guoguo-ux** [comment]
> Hi, you can ignore the warnings. The second one just means the 'event' variable is specified in the 'yreg' argument rather than the 'event' argument.

thank you very much

**Comment by Guoguo-ux** [comment]
> est <- cmest(data = data, model = "rb", outcome = "Y", exposure = "A",
> mediator = "M", basec = c("C1", "C2", "C3"), EMint = FALSE,
> mreg = list(lm(M ~ A+C1+C2, data = data)), yreg = lm(Y ~ A+M+C1+C2+C3, data = data),
> astar = 0, a = 1, mval = list(1),
> estimation = "imputation", inference = "bootstrap", nboot = 20)

the code from BS1125 is effective
est <- cmest(data = data, model = "rb", outcome = "Y", exposure = "A",
mediator = "M", basec = c("C1", "C2", "C3"), EMint = FALSE,
mreg = list(lm(M ~ A+C1+C2, data = data)), yreg = lm(Y ~ A+M+C1+C2+C3, data = data),
astar = 0, a = 1, mval = list(1),
estimation = "imputation", inference = "bootstrap", nboot = 20)
