### ISSUE TITLE
Approach to high-dimensional data with multiple mediators 

### ISSUE THREAD

**Issue by ChadFibke** [BS1125/CMAverse#25]
Hi @BS1125,

I'm currently working on a mediation analysis examining the mediating effect genetic mutations (for example single nucleotide polymorphisms [SNP] ) have on the relationship between an exposure and a disease. The genetic mutations are high dimensional, but can be reduced to a subset of selected mutations based on selection criteria, or reduced down to components.

Based of previous readings, using components in place of exposure/mediator/outcome variables can violates the casual assumptions of consistency and tend to complicate  the interpretation of the NIE . However, I was wondering if a multiple mediator model can be used in place of the component mediating variable? When looking at your  [overview](https://bs1125.github.io/CMAverse/articles/overview.html), it states "CMAverse estimates the joint mediated effect through the set of mediators". Does this joint estimate assume each mediator is independent of all other mediators, or is it possible to use mediators that are correlated with each other (for example a multiple SNPs selected through variable selection methods)? 

Best,
Chad

**Comment by BS1125** [comment]
Hi, yes, mediators in the joint estimation can be correlated with each other.
