### ISSUE TITLE
Continuous exposure

### ISSUE THREAD

**Issue by zhenqiufd** [BS1125/CMAverse#26]
Hi, thank you for your excellent jobs. I have two questions. 1) How to set the **a** and **astart** values when the exposure is a _continuous variable_ (e.g., blood pressure)?  2) When the exposure is a continuous variable, do the confounding adjustment could be done by the cmest? Thank you very much.

**Comment by Guoguo-ux** [comment]
astar = 0, a = 1.  or you can use a =1, a=2 . the result is same

**Comment by BS1125** [comment]
Hi, yes, the exposure can be continuous. a and astar are two reference values of interest. The causal effects are interpreted as the change of the outcome if you change the exposure from astar to a. So, they could be any values (of the exposure) you are interested in.
