### ISSUE TITLE
Codes in appendix of "Effect decomposition in the presence of an exposure-induced mediator-outcome confounder" 

### ISSUE THREAD

**Issue by Guoguo-ux** [BS1125/CMAverse#27]
It seems like cmaverse cant't compute path-specific effect when there is an exposure-induced confounder, so I try to use SAS codes in the appendix of "Effect decomposition in the presence of an exposure-induced mediator-outcome confounder" to calculate path-specific effect. However, these SAS codes doesn't work. The main problems are the conditional statements, as shown in P1. In the dataset selected by "where (a = 1) & (astarstar = 0)", the only value of astar is 0, so "model y = astar" doesn't work. Similarly，"model y = astarstar" doesn't work due to "where (a = 1) & (astar = 1)". Can you help me figure out the problems? Thanks in advance!

**Comment by BS1125** [comment]
Hi, I'm not familiar with SAS codes and it's perhaps a better idea to ask the author of the codes.
