### ISSUE TITLE
Misclassification with categorical exposure

### ISSUE THREAD

**Issue by jeffbone** [BS1125/CMAverse#28]
Hello,

Thanks for the great package! 

I am having some issues with `cmsens` when I have a categorical exposure with measurement error and couldn't find a solution in the documentation files. I have a four-level factor as exposure, and am passing the following misclassification matrix to `cmsens`:

```ruby
MEerror = list(matrix(c(0.95, 0.05, 0.00, 0.00,
                        0.05, 0.90, 0.05, 0.00,
                        0.00, 0.05, 0.90, 0.05,
                        0.00, 0.00, 0.05, 0.95), nrow = 4)
```

When I run the function however, I get the following error: 

```ruby
Error in simexreg(reg = list(coefficients = c(`(Intercept)` = -5.72545289220289,  : 
  MEerror may contain negative values for exponents smaller than 1
```

Not sure what to make of this, my model for the outcome regression has a negative intercept, and a negative coefficient for one level of my exposure - is this the issue?

Any thoughts much appreciated.

Jeff

**Comment by BS1125** [comment]
Hi, the misclassification matrix has to fulfill some conditions (the matrix you provide fails). This function can be used to check the conditions, simex::check.mc.matrix(), for which TRUE means the conditions are satisfied. You can also use this function simex::build.mc.matrix() to obtain a valid misclassification matrix nearest to the matrix you provide (sometimes it fails to find one so you need to slightly change the matrix you provide and try again). 
For example, this matrix is valid and is close to your matrix:
          [,1]      [,2]      [,3]      [,4]
[1,] 0.9486019 0.0499638 0.0013675 0.0000741
[2,] 0.0499638 0.9086621 0.0499994 0.0013675
[3,] 0.0013675 0.0499994 0.9086621 0.0499638
[4,] 0.0000741 0.0013675 0.0499638 0.9486019

**Comment by jeffbone** [comment]
This is great - thank you! 

Jeff
