### ISSUE TITLE
More significant figures on P-value in Effect decomposition table

### ISSUE THREAD

**Issue by la-mendicino** [BS1125/CMAverse#29]
Hi,

Obligatory love your package and appreciate all the work that went into it!

I am wondering how to get more digits on the P-value in the effect decomposition table. Any help would be greatly appreciated, thanks!

Best,

Lucas

**Comment by BS1125** [comment]
Hi, p values are saved in the object, e.g., 
exp1 <- cmest(data = cma2020, model = "rb", outcome = "contY", 
              exposure = "A", mediator = "M2", basec = c("C1", "C2"), 
              EMint = FALSE, mreg = list("multinomial"), yreg = "linear", 
              astar = 0, a = 1, mval = list("M2_0"), estimation = "paramfunc", 
              inference = "delta")
> exp1$effect.pval
         cde         pnde         tnde         pnie         tnie           te 
1.334488e-13 1.334488e-13 1.334488e-13 1.154191e-01 1.154191e-01 3.415312e-11 
          pm 
1.488973e-01

**Comment by la-mendicino** [comment]
Sweet, thank you!
