### ISSUE TITLE
Issue with CMAverse Imputation of Randomized Analogue Model

### ISSUE THREAD

**Issue by chigg2** [BS1125/CMAverse#34]
I have been working on imputing some mediation models using the gformula in the CMAverse. My model has two mediators (M0) and (M1), with M0 being a mediator ("L") affected by exposure (A). In my model, M0, M1, and A are dichotomous, and Y is a continuous variables. So far, I successfully run these models in my own computer using multiple imputation, m=10, and nboot=100. However, since these models are computational intensive and we wanted to increase the numbers of boots to 1000, we decided to use the cluster computer at my university. But, the cluster version of the CMAverse is throwing us an error, even when we use the simulated data suggested in your website.  

When I run the following R script in the cluster computer using the R version is 4.2.0, and the CMAverse version CMAverse_0.1.0., we keep getting the same error. 

 0%Error: variable 'M' was fitted with type "numeric" but type "logical" was supplied

However, when I run this same script in my desktop computer, I am able to obtain the randomized analogue model mediation results. My desktop computer R version is 3.6.2, and CMAverse version is CMAverse_0.1.0. We thought that perhaps by running the same R version I have in my computer  in the cluster, we would be able to fix the issue. But, we were unsuccessful. We are wondering if this might be a bug of the package or if someone has run into this issue too. We appreciate any help with this matter. 

Best 

**Code run in the cluster that generates error message** 
![Screen Shot 2023-03-31 at 6 12 49 PM](https://user-images.githubusercontent.com/48980673/229242149-6f612989-1e54-4860-a43f-292e7b0ef9f1.png)

**Results from same code in my desktop computer** 
<img width="1188" alt="Screen Shot 2023/-/03-31 at 6 29 07 PM" src="https://user-images.githubusercontent.com/48980673/229243919-82d51135-7060-4ab7-9c1a-c40f246263c9.png">

**Comment by ChadFibke** [comment]
Hi @chigg2,

When you run your code, you set `outcome = "C1"`, when it should be `outcome = Y"`. Does this solve the issue? If the issue still persists, can you rerun the code and send the output of `traceback()`?

Best,
Chad

**Comment by BS1125** [comment]
Hi, I'm not sure what happend in Cluster but you could try change your M to a factor by M = as.factor(M) before running cmest().
