### ISSUE TITLE
variable type error

### ISSUE THREAD

**Issue by rzimba** [BS1125/CMAverse#38]
I am new to CMAverse and am trying to fit my first model. I have one mediator which is length of stay. I would like to model this as a count variable using the Poisson distribution (it is highly skewed), however I get the following error message, even though the variable is an integer. I have tried converting the variable to numeric but I still get the error message. 

`Error: variable 'losint' was fitted with type "numeric" but type "character" was supplied`

```
cma.est <- cmest(data=lc, model="rb", 
                 outcome = "postdcinf",
                 exposure = "abxnone",
                 mediator = "losint",
                 basec = c("age","agesq","open","op_time"),
                 EMint = FALSE,
                 mreg = list("poisson"),
                 yreg = "logistic",
                 astar = 0,
                 a = 1,
                 mval = list("losint_0"),
                 yval = 1,
                 estimation = "imputation",
                 inference = "bootstrap")

summary(cma.est)
```

The data has been slightly modified from a publicly available RCT [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0106702#s5) so that the reference category for "abxnone" is assigned to treatment and the reference category for "open" is laparoscopic cholecystectomy. All infectious complications  coded as "Wound infection", "Urinary infection", "Respiratory infection" or "Prostatitis" are coded as 1 for postdcinf (post-discharge infection), and zero otherwise. I have excluded observations for other infectious complications except for "FUO" (which was not a primary endpoint).

**Comment by rzimba** [comment]
I changed mval to an integer and the code ran, but can I use the "losint_0" specification?

**Comment by BS1125** [comment]
Hi, mval must be a value of the mediator rather than its label.
