### ISSUE TITLE
Measurement error sensitivity analysis (incorrect number of dimensions)

### ISSUE THREAD

**Issue by vriesTR** [BS1125/CMAverse#39]
Thank you all your work on this R-package!

I have a brief question. I have used the regression-based approach to CMA for the following setting:
- Binary exposure
- 2 continous mediators
- Binary outcome
- 3 continous covariates and 1 binary covariate to adjust for confounding

I am trying to conduct a sensitivity analysis to asssess the impact of measurement error in my binary exposure with the following code:

mc <- matrix(c(0.90,0.10,0.10,0.90), nrow = 2)
mc2 <- simex::build.mc.matrix(mc)
sens_exposure <- cmsens(object = res_rb, 
                    sens = "me", 
                    MEmethod = "simex", 
                    MEvariable = "Abuse_any", 
                    MEvartype = "cat", 
                    MEerror = list(mc2))

summary(sens_exposure)

I obtain the following error: 

Error in simexreg(reg = list(coefficients = c(`(Intercept)` = -2.19353928486105,  : 
  Incorrect dimension of MEerror

The original code was where I specified the MEerror variable as list(mc), but I checked another thread where it was suggested to use simex::build.mc.matrix() to build a matrix that is similar to the original one (mc in my case). Is my error perhaps due to the fact that I have 2 mediators in my model? 

Any help would be very welcome! Thanks in advance.

**Comment by BS1125** [comment]
Hi, the dimension of the mc should equal to the number of ME variables. So in your case, the mc should be a scalar if the MEvariable is "Abuse_any" only.

**Comment by vriesTR** [comment]
Hi, thank you for your reply. I have yet been able to get the code to work.

Interestingly, the vignette pertaining to measurement error (https://bs1125.github.io/CMAverse/articles/measurement_error.html) uses the exact same code as I am in my script. The vignette also includes a binary exposure variable. In the vignette the same mc matrix as I have provided in the abovementioned code is used (mc <- [matrix](https://rdrr.io/r/base/matrix.html)([c](https://rdrr.io/r/base/c.html)(0.9,0.1,0.1,0.9), nrow = 2)). The vignette works fine, but my code doesn't. Perhaps the issue lies elsewhere?

**Comment by BS1125** [comment]
I see. Abuse_any is binary But have you checked it only has two categories? The error you got means the number of rows in mc doesn't equal to the number of categories of Abuse_any. You may print Abuse_any to see if there are more than 2 values.
