### ISSUE TITLE
Continuous mediator

### ISSUE THREAD

**Issue by YuHao0099** [BS1125/CMAverse#40]
Hi, thank you for your excellent packages! We have known that the "mval" arguments referred to a list specifying a value for each variable in mediator at which the variable is controlled. However, in the example of "Statistical Modeling with a Single Mediator", you used "mval = list(1)" for a binominal mediator. I am wondering the reason why the control value for the mediator is not 0, because we could see the control value for the binominal exposure in the same example is set to 0 (astar = 0). Further, I am also mixed up about the right value (0 or 1?) when the mediator is a continuous variable. Is there any instruction to set the "mval = list( )" values for continuous and binominal mediators? Thank you in advance!

**Comment by BS1125** [comment]
Hi, mval is usually set to any values of interest. For a continuous mediator, this could be the mean.

**Comment by YuHao0099** [comment]
> Hi, mval is usually set to any values of interest. For a continuous mediator, this could be the mean.

This is great - thank you!

Yu
