### ISSUE TITLE
Can multiple imputation be performed with model="wb"?

### ISSUE THREAD

**Issue by Apprentice2** [BS1125/CMAverse#42]
Thank you for developing this wonderful software.

I would like to do a mediation analysis with a weighting-based approach (wb). I would also like to use multiple imputation as the covariates contain some missing values. So I tried the following command.

------------------------------------
est <- cmest(data = data , model = "wb", 
              outcome  = "O", 
              exposure = "A",
              mediator = "M", 
              basec    = c("age","sex"), 
              EMint    = FALSE,
              ereg     = "logistic", 
              yreg     = "logistic",
              astar = 0, a = 1, mval = list(mean(data$M)), yval=1,
              estimation = "imputation", inference = "bootstrap", nboot = 1000, 
              multimp=TRUE, m=100)
summary(est)
------------------------------------

Then, although a warning message "Warning in regrun() :   mreg is ignored when model is 'wb', 'iorw' or 'ne'" was displayed, the calculation seemed to be completed. However, when I looked at the results in summary(est), the results for multiple datasets were not displayed, and it appeared that multiple imputation was not performed.

Is it not possible to perform multiple imputation when model="wb"?

**Comment by BS1125** [comment]
Hi, multiple imputation can be implemented for wb. We only show the final results rather than the results for each imputed dataset.

**Comment by Apprentice2** [comment]
Thank you for your reply.

I ran cmest with the combination of model="wb" and multiple imputation and it looked like the number of datasets m in multiple imputation was not working.
The following scripts were implemented

-------------------------------------------------------------
set.seed(1)
expit <- function(x) exp(x)/(1+exp(x))
n <- 10000
C1 <- rnorm(n, mean = 1, sd = 0.1)
C2 <- rbinom(n, 1, 0.6)
A <- rbinom(n, 1, expit(0.2 + 0.5*C1 + 0.1*C2))
M <- rnorm(n, 1 + 0.2*A + 0.15*C1 + 0.08*C2,sd=1)/10
Y <- rbinom(n, 1, expit(-3 - 0.4*A - 1.2*M + 0.5*A*M + 0.3*C1 - 0.6*C2))
data_noNA <- data.frame(A, M, Y, C1, C2)
missing <- sample(1:(5*n), n*0.1, replace = FALSE)
C1[missing[which(missing <= n)]] <- NA
C2[missing[which((missing > n)*(missing <= 2*n) == 1)] - n] <- NA
A[missing[which((missing > 2*n)*(missing <= 3*n) == 1)] - 2*n] <- NA
M[missing[which((missing > 3*n)*(missing <= 4*n) == 1)] - 3*n] <- NA
Y[missing[which((missing > 4*n)*(missing <= 5*n) == 1)] - 4*n] <- NA
data <- data.frame(A, M, Y, C1, C2)

library(CMAverse)

#model rb
system.time(res_multimp_rb <- cmest(data = data_noNA, model = "rb", outcome = "Y", exposure = "A",
                     mediator = "M", basec = c("C1", "C2"), EMint = TRUE,
                     mreg = list("linear"), yreg = "logistic",
                     astar = 0, a = 1, mval = list(1), 
                     estimation = "imputation", inference = "bootstrap", nboot=100,
                     multimp = TRUE, m = 10))

summary(res_multimp_rb)
length(res_multimp_rb$reg.output )
res_multimp_rb$multimp$args_mice$m
 
#model wb
system.time(res_multimp_wb <- cmest(data = data, model = "wb", outcome = "Y", exposure = "A",
                     mediator = "M", basec = c("C1", "C2"), EMint = TRUE,
                     ereg = "logistic", yreg = "logistic",
                     astar = 0, a = 1, mval = list(1), 
                     estimation = "imputation", inference = "bootstrap", nboot=100,
                     multimp = TRUE, m = 10))

summary(res_multimp_wb)
length(res_multimp_wb$reg.output )
res_multimp_wb$multimp$args_mice$m
 
-------------------------------------------------------------

As shown above, I created "res_multimp_rb" by performing cmest with model="rb" and m=10, and "res_multimp_wb" by performing cmest with model="wb" and m=10.

When the summary function is applied to each object, the results of 10 data sets are displayed for rb, but only 5 data sets are displayed for wb.

I think the specification is that res_multimp_rb$multimp$args_mice$m and res_multimp_wb$multimp$args_mice$m have the parameter m for the number of data sets passed to mice. In fact, res_multimp_rb$multimp$args_mice$m was 10, but res_multimp_wb$multimp$args_mice$m was NULL. 

MICE is performed with m=5 by default if m is not specified. This observation seems to indicate that the number of data sets for multiple imputation is not passed to mice when model="wb", how about it?

**Comment by BS1125** [comment]
Hi, this issue has been fixed. It's because arguments can be matched by prefix matching in R, and m was matched with mreg. Could update the package and try again? Please let me know if there are any issues about this update. Thank you!

**Comment by Apprentice2** [comment]
Thank you very much for your prompt implementation of the fix. I reinstalled the latest version of CMAverse and performed the following command and it worked.

 res_multimp_wb <- cmest(data = data, model = "wb", outcome = "Y", exposure = "A",
                      mediator = "M", basec = c("C1", "C2"), EMint = TRUE,
                      ereg = "logistic", yreg = "logistic", 
                      astar = 0, a = 1, mval = list(1), 
                      estimation = "imputation", inference = "bootstrap", nboot=10,
                      multimp = TRUE, args_mice=list(m = 10))
