### ISSUE TITLE
Effect estimates are not contained within provided confidence intervals

### ISSUE THREAD

**Issue by JAGoodrich** [BS1125/CMAverse#50]
On the CMAverse website, under the statistical modeling with a single mediator example, the following code results in Rpnie, Rtnie and other estimates which are not within the provided 95% confidence intervals:

```{r}
res_rb_param_bootstrap <- cmest(data = data, model = "rb", outcome = "Y", exposure = "A",
                                mediator = "M", basec = c("C1", "C2"), EMint = TRUE,
                                mreg = list("logistic"), yreg = "logistic",
                                astar = 0, a = 1, mval = list(1), 
                                estimation = "paramfunc", inference = "bootstrap", nboot = 2)
```

This code is under the heading "Closed-form Parameter Function Estimation and Bootstrap Inference". We have replicated this issue in some of our analyses as well.

**Comment by BS1125** [comment]
Hi, to get a good confidence interval, nboot (the number of boostraps) shouldn't be too small. Please try nboot = 200 or  more.
