### ISSUE TITLE
Unable to account for complex survey design

### ISSUE THREAD

**Issue by kodalih** [BS1125/CMAverse#53]
First, thanks for working on the package and making it publicly available. 

I am using your package "CMAverse" to perform a single mediator analysis in the Nationally representative survey- NHANES. I have created a survey design object and added it to the model as data. However, the results of causal mediation analysis are the same for both unweighted and weighted (accounting for complex survey design) datasets. My understanding about the CMAverse package is that it can account for survey design to provide estimation, however, the codes neglect the survey's complex structure.

#to create survey object
survey_object <- analysis_data %>% 
    as_survey_design(id = SDMVPSU, strata = SDMVSTRA, weights = WTMEC4YR, nest = TRUE)

#Estimate causal effects and make inferences using cmest
set.seed(2021)
cma_model <- cmest(data = survey_object, 
                   model = "rb", 
                   outcome ="permth_int",
                   event = "mortstat",
                   exposure = "Exposure",
                   mediator = "Mediator",
                   basec = c("Confounder1", "Confounder2"),  
                   EMint = TRUE,
                   mreg = list("linear"), yreg = "coxph",
                   astar = 2, a = 7, mval = list(0), 
                   estimation = "imputation", inference = "bootstrap", nboot = 10000)

Do you have any suggestions about how I can account for complex surveys? 

Thank you for your time and consideration.

Regards, 

Hanish

**Comment by BS1125** [comment]
Hi Hanish, if you set mreg = list("linear") and yreg = "coxph", then the package will fit unweighted regression models for you and use them in mediation analysis. To use weighted regression models, you need to set mreg and yreg to the weighted regression models, i.e., lm() fitted with weights and coxph() fitted with weights, that were fitted before using cmest. Please check the examples.
