### ISSUE TITLE
cmest fails to run when passing 'predictorMatrix' and 'method' arguments to 'args_mice'

### ISSUE THREAD

**Issue by lsteell** [BS1125/CMAverse#56]
Thank you for this excellent package, it has made the implementation of CMA very accessible!

I am attempting to use CMAverse to complete an analyses with the ```gformula``` approach but the ```cmest``` fails to run when I attempt to pass arguments to ```args_mice```. Particularly, when I attempt to use pre-defined ```method``` and ```predictorMatrix``` arguments.

My analyses include two broad phases:

1. 'Traditional' epi models: X -> Y, M -> Y. For these models, I am using the ```mice``` package to impute missing data for analyses.

2. CMA. Here, I'd like to use the same methods for imputation defined in ```mice``` from phase one above to maintain consistency (namely the same ```method``` and ```predictorMatrix```).  

For CMA, I'm using the following syntax:

```
cma1 <- cmest(data = data,
                          model = "gformula",
                          estimation = "imputation",
                          inference = "bootstrap",
                          outcome = "outcome",
                          exposure = "education",
                          mediator = c("obese_bmi"), 
                          EMint = FALSE,
                          basec = c("sex", "ethnic_group", "birth_year", "imd_quantile", "avg_house_income"),
                          postc = c("ipaq_grp", "smoking_status", "alcohol_freq"),
                          yreg = "poisson",          
                          mreg = list("logistic"),
                          postcreg = list("ordinal", "multinomial", "multinomial"),
                          astar = "Degree",          
                          a = "None",  
                          mval = list(0),        
                          nboot = 400, 
                          boot.ci.type = "per", 
                          multimp = TRUE,
                          args_mice = list(meth = meth, predictorMatrix = predM, maxit = 10, seed = 123))
```

The above ```cmest``` call results in the following error message: 
```Error in `[.data.frame`(data, , vname, drop = FALSE) : 
  undefined columns selected```

I have double checked that all columns are within the dataframe and are spelled correctly.

When the ```predictorMatrix``` and ```method``` arguments are dropped, the ```cmest``` call works - however it does not apply the desired methods of imputation that I previously specified for analyses completed before CMA - meaning phase 1 & 2 of analyses are on different data.

The dataset 'data' has more variables than will be included in the CMA analyses - might this be the reason ```cmest``` is unable to run? If so, are there any available work arounds to resolve this?

Interestingly, I've come across another individual on stackoverflow who has reported the same issue, so far without resolution (https://stackoverflow.com/questions/78190882/passing-arguments-through-the-mice-function-within-the-cmest-function-from-the-c). 

Your help is very much appreciated.

**Comment by BS1125** [comment]
Hi that's because we reduce the dataset to include only exposure, outcome, mediator and confounders. I have removed this reduction. Thank you for raising this point. Can you try again and let me know if predictorMatrix works?
